CREATE TABLE prices
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    brand_id   BIGINT         NOT NULL,
    start_date TIMESTAMP WITH TIME ZONE NOT NULL,
    end_date   TIMESTAMP WITH TIME ZONE NOT NULL,
    price_list BIGINT         NOT NULL,
    product_id BIGINT         NOT NULL,
    priority   INT            NOT NULL,
    price      DECIMAL(10, 2) NOT NULL,
    currency   VARCHAR(3)     NOT NULL,
    CONSTRAINT chk_prices_valid_period CHECK (start_date <= end_date)
);
